---
#
# Add flathub support and install packages
#

- name: "Add the flathub flatpak repository"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user


- name: "Install slack"
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: user
  loop:
    - "com.slack.Slack"
    - "com.microsoft.Teams"
    - "com.getpostman.Postman"
    - "com.bitwarden.desktop"

