---
#------------------------------------------------------------------------------
# Configuration with dconf
# see: https://docs.ansible.com/ansible/2.9/modules/dconf_module.html
#------------------------------------------------------------------------------

- name: Apply dconf settings.
  become_user: '{{ user.name }}'
  dconf:
    key: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items: '{{ user.dconf }}'
